#!/usr/bin/env bash
# Print the unresolved review threads of a pull request as JSON, one object per thread.
# Usage: threads.sh <owner/repo> <pr-number> [--all | --reviews]
# Without --all, only threads whose first comment comes from a bot account or
# carries an AI disclosure line are printed. Each object has: id (GraphQL thread
# id for resolveReviewThread), path, line, author, ai (bool), comment_id (REST id
# of the first comment, for replies), url, body (first comment), replies (count),
# outdated (bool).
set -euo pipefail
# A mise-managed gh wrapper prints status lines to stdout, which breaks jq.
export MISE_QUIET=1
repo="${1:?owner/repo}"; pr="${2:?pr number}"; all="${3:-}"
owner="${repo%%/*}"; name="${repo##*/}"
if [ "$all" = "--reviews" ]; then
  # Bot review bodies: CodeRabbit "Outside diff range" and "Nitpick" items, Codex and Gemini summaries.
  gh api --paginate "repos/$repo/pulls/$pr/reviews" | jq -s 'add
    | [.[] | select((.user.type=="Bot") or (.user.login|test("\\[bot\\]$"))) | select(.body|length>0)
      | {review_id:.id, author:.user.login, submitted_at, state, commit:.commit_id, body}]'
  exit 0
fi
cursor=null; out='[]'
while :; do
  page=$(gh api graphql -f query='
    query($owner:String!,$name:String!,$pr:Int!,$cursor:String){
      repository(owner:$owner,name:$name){ pullRequest(number:$pr){
        reviewThreads(first:100,after:$cursor){
          pageInfo{hasNextPage endCursor}
          nodes{ id isResolved isOutdated path line originalLine
            comments(first:50){ totalCount nodes{ databaseId url body
              author{ login __typename } } } } } } } }' \
    -F owner="$owner" -F name="$name" -F pr="$pr" -F cursor="$cursor" 2>/dev/null)
  out=$(jq -c --argjson prev "$out" '
    $prev + [.data.repository.pullRequest.reviewThreads.nodes[]
      | select(.isResolved|not)
      | (.comments.nodes[0]) as $c
      | {id, path, line:(.line // .originalLine), outdated:.isOutdated,
         author:$c.author.login,
         ai:(($c.author.__typename=="Bot") or ($c.author.login|test("\\[bot\\]$"))
             or ($c.body|test("generated by AI|Generated by (Copilot|Codex|Claude|Gemini)";"i"))),
         comment_id:$c.databaseId, url:$c.url, body:$c.body,
         replies:(.comments.totalCount-1)}]' <<<"$page")
  if [ "$(jq -r '.data.repository.pullRequest.reviewThreads.pageInfo.hasNextPage' <<<"$page")" != true ]; then break; fi
  cursor=$(jq -r '.data.repository.pullRequest.reviewThreads.pageInfo.endCursor' <<<"$page")
done
if [ "$all" = "--all" ]; then jq '.' <<<"$out"; else jq '[.[]|select(.ai)]' <<<"$out"; fi
